services:
  stainless:
    build: 
      context: .
      dockerfile: ./infra/docker/stainless/Dockerfile
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: ["bash", "-c", "stainless $(find ./src/main/scala -name '*.scala' | tr '\n' ' ')"]
